require("react-hot-loader/patch")
require("babel-runtime/regenerator")
require("babel-register")
require("webpack-hot-middleware/client?reload=true")
// require("./main.css")
// require("./main.styl")
// require("./main.sass")
require("./images/link.jpg")
require("./index.ejs")
require("./app")
